# Generated by Django 4.2.5 on 2023-09-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('visitor', 'visitor'), ('moderator', 'moderator')], max_length=20, null=True),
        ),
    ]
