# Generated by Django 4.2.5 on 2023-09-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Название')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='Изображение')),
                ('desc', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Название')),
                ('desc', models.TextField(blank=True, max_length=250, null=True, verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='courses', verbose_name='Изображение')),
                ('link', models.URLField(verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
