# Generated by Django 4.2.5 on 2023-09-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_course_buyer_lesson_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='оплачено'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(default='NULL', max_length=100, verbose_name='id_платежа'),
        ),
    ]
